name: Сборка Flatpak для AyuGram

on:
  workflow_dispatch:

jobs:
  build-flatpak:
    name: Сборка и упаковка Flatpak
    runs-on: self-hosted

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Инициализация подмодулей
        run: |
          git submodule update --init --recursive --force
          git submodule foreach --recursive 'git checkout HEAD || git checkout master || git checkout main || true'

      - name: Установка зависимостей и Flatpak SDK
        run: |
          sudo dnf install -y flatpak flatpak-builder python3-pip
          pip3 install poetry
          flatpak install -y --noninteractive org.gnome.Sdk//48

      - name: Подготовка библиотек
        run: ./Telegram/build/prepare/linux.sh

      - name: Сборка бинарного файла AyuGram
        env:
          TDESKTOP_API_ID: ${{ secrets.TDESKTOP_API_ID }}
          TDESKTOP_API_HASH: ${{ secrets.TDESKTOP_API_HASH }}
        run: |
          docker run --rm \
            -u $(id -u) \
            -v "$PWD:/usr/src/tdesktop" \
            ghcr.io/telegramdesktop/tdesktop/centos_env:latest \
            /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
            -D TDESKTOP_API_ID=${TDESKTOP_API_ID} \
            -D TDESKTOP_API_HASH=${TDESKTOP_API_HASH}

      - name: Подготовка директории для сборки Flatpak
        run: |
          mkdir ayugram-flatpak-build
          cp out/Release/AyuGram ayugram-flatpak-build/
          cp -r docs/assets/flatpak-files/* ayugram-flatpak-build/

      - name: Определение версии приложения
        id: get_version
        run: |
          APP_VERSION=$(grep '<release version=' docs/assets/flatpak-files/usr/share/metainfo/com.ayugram.desktop.metainfo.xml | sed -n 's/.*version="\([^"]*\)".*/\1/p')
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "Найдена версия: ${APP_VERSION}"

      - name: Сборка Flatpak пакета
        run: |
          rm -rf repo build-dir
          flatpak-builder --repo=repo --force-clean --disable-rofiles-fuse build-dir com.ayugram.desktop.yml
          flatpak build-bundle repo ayugram-desktop-${{ env.APP_VERSION }}.flatpak com.ayugram.desktop
        working-directory: ./ayugram-flatpak-build

      - name: Загрузка артефакта
        uses: actions/upload-artifact@v4
        with:
          name: ayugram-flatpak-package
          path: ayugram-flatpak-build/ayugram-desktop-*.flatpak
          retention-days: 15